var skills = [
  {
    id: "html1",
    name: `Have a buddy "code" HTML for you`,
    description: "He used to make websites back in the dot com boom of the 90's, and probably still knows what he's doing. He can add a background to your website and make it a bit snazzier.",
    cost: 5,
    trigger: 5,
  },
  {
    id: "html2",
    name: "Loan a used copy of HTML for Dummies",
    description: "If you're gonna start adding content to your website, you'd better know how to mark it up. This book is an excellent resource and teaches you the state-of-the-art HTML 4.0.",
    cost: 10,
    trigger: 5,
    prerequisites: [ 'html1' ],
  },
  {
    id: "startup",
    name: `Become a "startup"`,
    description: "You decide that this web thing isn't so bad, and that you wanna start a startup. You don't know what your business model will be yet, but now that you know a bit of code, it'll be easier to get started.",
    cost: 15,
    trigger: 5,
    prerequisites: [ 'html2' ],
  },
  {
    id: "css1",
    name: "Learn CSS",
    description: "Your new Graphic Design team needs to know some CSS in order to make the website look a little better.",
    team: "Graphic Design",
    cost: 25,
    trigger: 10,
    multiplier: 0.01,
  },
  {
    id: "favicon",
    name: "What's a favicon?",
    description: "A buddy was adding your website to favourites when he realized your page didn't have an actual icon. He tells you what a favicon is and how to set it up, but you just keep it simple for now.",
    team: "Graphic Design",
    cost: 25,
    trigger: 10,
    multiplier: 0.01,
  },
  {
    id: "fireworks",
    name: "Learn Macromedia Fireworks",
    description: "Your Graphic Design team needs some software to design your site. You obtain a copy of Macromedia Fireworks for them to do the mockups in and they take the site to the next level.",
    team: "Graphic Design",
    cost: 25,
    trigger: 10,
    multiplier: 0.01,
  },
  {
    id: "monetize",
    name: "Monetize with ads",
    description: "You're getting views, but your wallet is getting emptier because of server costs...running a startup is harder than your thought.",
    team: "Graphic Design",
    cost: 25,
    trigger: 10,
    multiplier: 0.01,
  },
  {
    id: "javascript",
    name: "Learn JavaScript",
    description: "You recently heard about DHTML, and decided that you should step up your game and pay for the front end developers to learn some JavaScript so they can make collapsable menus.",
    team: "Front End Developers",
    cost: 25,
    trigger: 10,
    multiplier: 0.01,
  },
];

export default skills;
